name: Bworkflow

on:
  push:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository that triggers the event'
        required: false
      run_id:
        description: 'Workflow run ID that triggers the event'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
