name: Tests Run button

on:
  push:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository that triggers the event'
        required: false
      run_id:
        description: 'Workflow run ID that triggers the event'
        required: false
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.inputs.repo }}
      - run: echo ${{ github.event.inputs.run_id }}
